Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetBook.Data;
using PetBook.Models;
using Microsoft.EntityFrameworkCore;


namespace PetBook.Controllers
{
    public class CalendarController : Controller
    {
        private PetbookContext dbContext;

        public CalendarController(PetbookContext dbContext)
        {
            this.dbContext = dbContext;
        }
        // GET: Calendar
        public IActionResult IndexCalendar()
        {
            var model = dbContext.Client
                                     .Where(client => client.UserEMail == User.Identity.Name)
                                     .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {

                var cal = this.dbContext.Calendar.AsEnumerable<Calendar>();
                  
                return View(cal);
            }
            else
            {
                return View("You currently have no events");
            }
            
        }
        public IActionResult DetailsCalendar(Calendar cal)
        {
            return View(cal);
        }
        
        // GET: Calendar/Create
        public IActionResult CreateCalendar()
        {
            
                
                return View();
        }

        // POST: Calendar/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCalendarPost(Calendar cal)
        {
            try
            {
                var model = dbContext.Client
                                    .Where(client => client.UserEMail == User.Identity.Name)
                                    .SingleOrDefault();

                if (model.UserEMail == User.Identity.Name)
                {

                    var PetCal = this.dbContext.Calendar.AsEnumerable()
                        .Select(PetCal => PetCal.CalendarId);
                    int [] CalId = PetCal.ToArray();
                    cal.CalendarId = HighestId(CalId);
                    cal.CalendarId++;


                    dbContext.Add(cal);
                    dbContext.SaveChanges();

                    return View("DetailsCalendar");
                }
                return View("DetailsCalendar");
            }
            catch
            {
                return View("IndexCalendar");
            }
        }

        // GET: Calendar/Edit/5
        public IActionResult EditCalendar(int id)
        {
            var model = dbContext.Client
                                    .Where(client => client.UserEMail == User.Identity.Name)
                                    .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {
                var cal = dbContext.Calendar
                    .Select(cal => cal.CalendarId == id);

                return View(cal);
            }
            else
            {
                return View("Error");
            }
        }

        // POST: Calendar/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCalendar(Calendar calendar)
        {
            try
            {
                dbContext.Update(calendar);
                dbContext.SaveChanges();

                return RedirectToAction("IndexCalendar");
            }
            catch
            {
                return Redirect("~/Shared/Error");
            }
        }

        // GET: Calendar/Delete/5
        public IActionResult DeleteCalendar(int id)
        {
            var model = dbContext.Client
                                    .Where(client => client.UserEMail == User.Identity.Name)
                                    .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {
                var cal = dbContext.Calendar
                    .Select(cal => cal.CalendarId == id);

                return View(cal);
            }
            else
            {
                return View("Error");
            }
        }

        // POST: Calendar/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCalendar(Calendar calendar)
        {
            try
            {
                dbContext.Remove(calendar);
                dbContext.SaveChanges();

                return RedirectToAction("IndexCalendar");
            }
            catch
            {
                return Redirect("~/Shared/Error");
            }
        }
        public static int HighestId(int [] CalId)
        {
            int id = 0;
            for (int i = 0; i < CalId.Length; i++)
            {
                
                if (CalId[i] == 0)
                {
                    continue;
                }
                else if (CalId[i] < id)
                {
                    continue;
                }
                else if (CalId[i] > id)
                {
                    id = CalId[i];
                    continue;
                }
                return id;
            }
            return id;
        }
    }
}

Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetBook.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using PetBook.Data;


namespace PetBook.Controllers
{
    public class ClientController : Controller
    {
        private PetbookContext dbContext;

        public ClientController(PetbookContext dbContext)
        {
            this.dbContext = dbContext;
        }
       
        public IActionResult FindClient(Client client)
        {
            try
            {
                var model = dbContext.Client
                                         .Where(client => client.UserEMail == User.Identity.Name)
                                         .SingleOrDefault();

                if (model.UserEMail == User.Identity.Name)
                {

                    return Redirect("~/Home/Dashboard");
                }
                else
                {
                    return View("CreateClient");
                }
            }
            catch
            {
                return Redirect("~/Home/PetBookHomePage");
            }
        }

        // Create a new client (registration)
        [HttpGet]
        public ActionResult CreateClient(Client client)
        {
            var model = dbContext.Client
                                        .Where(client => client.UserEMail == User.Identity.Name)
                                        .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {

                return Redirect("~/Home/Dashboard");
            }
            else
            {
                
                return View();
            }

        }

        // POST: Client/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateClientPost(Client client)
        {

           
                dbContext.Add(client);
                dbContext.SaveChanges();
            
                return RedirectToAction("DetailsClient");

            
        } 

        // GET: Client and Edit Client Details
        public IActionResult EditClient(Client client)
        {
            var model = dbContext.Client
                                       .Where(client => client.UserEMail == User.Identity.Name)
                                       .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {
                return View(model);
            }
            else
            {
                return Redirect("ClientDetails");
            }

        }

        // POST: Client/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditClientPost(Client client)
        {
            try
            {
                dbContext.Update(client);
                dbContext.SaveChanges();

                return RedirectToAction("DetailsClient");

            }
            catch
            {
                return Redirect("~/Home/Dashboard");
            }
        }

     
        // GET: Client Details and render on own view
        [HttpGet]
        public IActionResult DetailsClient(Client client)
        {
            var model = dbContext.Client
                                     .Where(client => client.UserEMail == User.Identity.Name)
                                     .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {

                return View(model);
            }
            else
            {
                return View("PetBookHomePage");
            }
        }
        // GET: Client Details and Display in a partial view for the Client Dashboard
        public ActionResult _DashboardClientDisplay(Client client)
        {
            var model = dbContext.Client;
                
                return View(model);
                
        }

        // GET: Client Delete Account
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Client Delete Account
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/MedicalFilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace PetBook.Controllers
{
    public class MedicalFilesController : Controller
    {
        // GET: MedicalFiles
        public ActionResult Index()
        {
            return View();
        }

        // GET: MedicalFiles/Details/5
        public ActionResult DetailsMedicalFile(int id)
        {
            return View();
        }

        // GET: MedicalFiles/Create
        public ActionResult AddMedicalFile()
        {
            return View();
        }

        // POST: MedicalFiles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMedicalFile(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicalFiles/Edit/5
        public ActionResult EditMedicalFile(int id)
        {
            return View();
        }

        // POST: MedicalFiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditMedicalFile(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicalFiles/Delete/5
        public ActionResult DeleteMedicalFile(int id)
        {
            return View();
        }

        // POST: MedicalFiles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMedicalFile(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  
   


</head>

<body>
    <style>
        body {
            background-image: url(../PetBookBG.png);
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container">
                <!--This is the navigation bar left image-->
                <div class="row">
                    <div class="col-2">
                        <img src="~/hunterdog.png" style="float:right" alt="hunterdog">
                    </div>
                </div>
                <!--This is the navigation bar-->
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="SiteInformation"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!--This is the navigation bar Welcome to PetBook-->
                    <ul class="navbar-nav flex-grow-1">
                        <div class="col-md-3">
                        </div>
                        <h1 class="display-4" style="color:black; padding-left:60px">Welcome to PetBook</h1>
                    </ul>
                </div>
            </div>



           
            <!--This is the navigation bar far right image-->
            <div class="row">
                <div class="col-11">
                    <img src="~/CompanyLogo.png" style="float:right" alt="Company Logo">
                </div>
            </div>
        </nav>

    </header>




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <div class="row"></div>

    <div class="container">
        <footer class="border-top footer text-muted" style="position:relative; padding: 5px">

            <div class="row"></div>
            <div class="col-12">
                <div class="container">
                    
                    &copy; 2020 - PetBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
                <script src="~/lib/jquery/dist/jquery.min.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
                @RenderSection("Scripts", required: false)
            </div>
        </footer>

    </div>




</body>
   
</html>

Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  
   


</head>

<body>
    <style>
        body {
            background-image: url(../PetBookBG.png);
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container">
                <div class="row">
                    <div class="col-2">
                        <img src="~/hunterdog.png" style="float:right" alt="hunterdog">
                    </div>
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Dashboard">PetBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dashboard">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Events List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="DetailsClient">Your Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicalFiles" asp-action="DetailsMedicalFile">Medical Files</a>
                        </li>
                    </ul>

                </div>
            </div>
            <div class="row">
                <div class="col-11">
                    <img src="~/CompanyLogo.png" style="float:right" alt="Company Logo">
                </div>
            </div>
        </nav>
        
    </header>




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <div class="row"></div>

    <div class="container">
        <footer class="border-top footer text-muted" style="position:relative; padding: 5px">

            <div class="row"></div>
            <div class="col-12">
                <div class="container">
                    @{ var theMonth = DateTime.Now.Month; }
                    &copy; 2020 - PetBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
                <script src="~/lib/jquery/dist/jquery.min.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
                @RenderSection("Scripts", required: false)
            </div>
        </footer>

    </div>




</body>
   
</html>