Models/Pet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PetBook.Models
{
    public partial class Pet
    {
        public Pet()
        {
            ClientPet = new HashSet<ClientPet>();
            MedicalFile = new HashSet<MedicalFile>();
            PetMed = new HashSet<PetMed>();
        }
        [Display(Name = "Pet Id #")]
        public int PetId { get; set; }

        [Required]
        [Display(Name = "Pet Name")]
        public string PetName { get; set; }

        [Required]
        [Display(Name = "Pet Species")]
        public string PetSpecies { get; set; }

        [Required]
        [Display(Name = "Pet Breed")]
        public string PetBreed { get; set; }

        [Required]
        [Display(Name = "Pet Sex")]
        public string PetSex { get; set; }

        [Required]
        [Display(Name = "Pet Age")]
        public int? Age { get; set; }

        public string PetImage { get; set; }
        public string PetProfileImagePath { get; set; }

        public virtual ICollection<ClientPet> ClientPet { get; set; }
        public virtual ICollection<MedicalFile> MedicalFile { get; set; }
        public virtual ICollection<PetMed> PetMed { get; set; }
    }
}

Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetBook.Data;
using PetBook.Models;
using Microsoft.EntityFrameworkCore;


namespace PetBook.Controllers
{
    public class CalendarController : Controller
    {
        private PetbookContext dbContext;

        public CalendarController(PetbookContext dbContext)
        {
            this.dbContext = dbContext;
        }
        // GET: Calendar
        public IActionResult IndexCalendar()
        {
            var model = dbContext.Client
                                     .Where(client => client.UserEMail == User.Identity.Name)
                                     .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {

                var cal = this.dbContext.Calendar.AsEnumerable<Calendar>();
                  
                return View(cal);
            }
            else
            {
                return View("You currently have no events");
            }
            
        }
        public IActionResult DetailsCalendar(Calendar cal)
        {
            return View(cal);
        }
        
        // GET: Calendar/Create
        public IActionResult CreateCalendar()
        {
            
                
                return View();
        }

        // POST: Calendar/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCalendarPost(Calendar cal)
        {
            try
            {
                var model = dbContext.Client
                                    .Where(client => client.UserEMail == User.Identity.Name)
                                    .SingleOrDefault();

                if (model.UserEMail == User.Identity.Name)
                {

                    var PetCal = this.dbContext.Calendar.AsEnumerable()
                        .Select(PetCal => PetCal.CalendarId);
                    int [] CalId = PetCal.ToArray();
                    cal.CalendarId = HighestId(CalId);
                    cal.CalendarId++;


                    dbContext.Add(cal);
                    dbContext.SaveChanges();

                    return View("DetailsCalendar");
                }
                return View("DetailsCalendar");
            }
            catch
            {
                return View("IndexCalendar");
            }
        }

        // GET: Calendar/Edit/5
        public IActionResult EditCalendar(int id)
        {
            var model = dbContext.Client
                                    .Where(client => client.UserEMail == User.Identity.Name)
                                    .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {
                var cal = dbContext.Calendar
                    .Select(cal => cal.CalendarId == id);

                return View(cal);
            }
            else
            {
                return View("Error");
            }
        }

        // POST: Calendar/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCalendar(Calendar calendar)
        {
            try
            {
                dbContext.Update(calendar);
                dbContext.SaveChanges();

                return RedirectToAction("IndexCalendar");
            }
            catch
            {
                return Redirect("~/Shared/Error");
            }
        }

        // GET: Calendar/Delete/5
        public IActionResult DeleteCalendar(int id)
        {
            var model = dbContext.Client
                                    .Where(client => client.UserEMail == User.Identity.Name)
                                    .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {
                var cal = dbContext.Calendar
                    .Select(cal => cal.CalendarId == id);

                return View(cal);
            }
            else
            {
                return View("Error");
            }
        }

        // POST: Calendar/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCalendar(Calendar calendar)
        {
            try
            {
                dbContext.Remove(calendar);
                dbContext.SaveChanges();

                return RedirectToAction("IndexCalendar");
            }
            catch
            {
                return Redirect("~/Shared/Error");
            }
        }
        public static int HighestId(int [] CalId)
        {
            int id = 0;
            for (int i = 0; i < CalId.Length; i++)
            {
                
                if (CalId[i] == 0)
                {
                    continue;
                }
                else if (CalId[i] < id)
                {
                    continue;
                }
                else if (CalId[i] > id)
                {
                    id = CalId[i];
                    continue;
                }
                return id;
            }
            return id;
        }
    }
}

Controllers/MedicalFilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace PetBook.Controllers
{
    public class MedicalFilesController : Controller
    {
        // GET: MedicalFiles
        public ActionResult Index()
        {
            return View();
        }

        // GET: MedicalFiles/Details/5
        public ActionResult DetailsMedicalFile(int id)
        {
            return View();
        }

        // GET: MedicalFiles/Create
        public ActionResult AddMedicalFile()
        {
            return View();
        }

        // POST: MedicalFiles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMedicalFile(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicalFiles/Edit/5
        public ActionResult EditMedicalFile(int id)
        {
            return View();
        }

        // POST: MedicalFiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditMedicalFile(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicalFiles/Delete/5
        public ActionResult DeleteMedicalFile(int id)
        {
            return View();
        }

        // POST: MedicalFiles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMedicalFile(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using PetBook.Data;
using PetBook.Models;


namespace PetBook.Controllers
{
    public class PetController : Controller
    {
        private PetbookContext dbContext;

        public PetController(PetbookContext dbContext)
        {
            this.dbContext = dbContext;
        }

        // GET: Pet/Details/5
        public IActionResult PetIndex()
        {
            var model = dbContext.Client
                                        .Where(client => client.UserEMail == User.Identity.Name)
                                        .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {

                return View(this.dbContext.Pet);
            }
        
            else
            {
                return Redirect("CreatePet");
            }
   
                
          
           
        }

        // GET: Pet/Create
        public IActionResult CreatePet()
        {
      
                return View();
           
        }

        // POST: Pet/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePetPost(Pet Pet)
        {
            try
            {
                dbContext.Add(Pet);
                dbContext.SaveChanges();

                return RedirectToAction("PetIndex");

             
            }
            catch
            {
                return View("PetIndex");
            }
        }

        // GET: Pet/Edit/5
        public IActionResult EditPet(int id)
        {

            var Pet = dbContext.Pet
                                      .Where(Pet => Pet.PetId == id)
                                      .SingleOrDefault();

            if (Pet.PetId == id)
            {

                return View(Pet);
            }
            else
            {
                return Redirect("PetIndex");
            }

        }

       

        // POST: Pet/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPetPost(Pet Pet)
        {
            try
            {
                dbContext.Update(Pet);
                dbContext.SaveChanges();

                return Redirect("PetIndex");


            }
            catch
            {
                return View("PetIndex");
            }
        }

        // GET: Pet/Delete/5
        public ActionResult RemovePet(int id)
        {
            var Pet = dbContext.Pet
                                     .Where(Pet => Pet.PetId == id)
                                     .SingleOrDefault();

            if (Pet.PetId == id)
            {

                return View(Pet);
            }
            else
            {
                return Redirect("PetIndex");
            }
           
        }

        // POST: Pet/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemovePet(Pet Pet)
        {
            try
            {
                dbContext.Remove(Pet);
                dbContext.SaveChanges();

                return RedirectToAction("PetIndex");


            }
            catch
            {
                return View("PetIndex");
            }
        }

        public ActionResult PetDashboard(int id)
        {
            var Pet = dbContext.Pet
                                      .Where(Pet => Pet.PetId == id)
                                      .SingleOrDefault();

            if (Pet.PetId == id)
            {
                
                return View(Pet);
            }
            else
            {
                return Redirect("PetIndex");
            }
           
        }
    }
}

Views/Pet/CreatePet.cshtml
@model PetBook.Models.Pet
@{
    ViewData["Title"] = "Create a Pet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


<div class="container-fluid" style="background-color: transparent">

    <!--This is the container for the body render-->
    <div class="container-fluid">
        <div class="card mb-lg-1" style="max-width:1200px; background-color: transparent; border-width: 0px">
            <div class="row">

                <!--This is the profile image-->
                <div class="col-md-3" style="padding: 30px">
                    <img src="~/ProfilePic.png" alt="User Profile" class="img-thumbnail">

                    <!--This is the side navigation bar-->
                    <!--TODO-->
                    <ul class="nav flex-column">
                        <li class="nav-item" style="padding-top:10px">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Dashboard">My Pets Profiles</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Veterinarian" asp-action="Create">Veterinarian Profile</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="CreateCalendar">Add Event</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="EditCalendar">Edit Event</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="DeleteCalendar">Delete Event</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="SiteInformation"></a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
                        </li>
                    </ul>
                </div>
                <div class="col-6" style="padding-left:0px">

                    <h4>Pet</h4>
                    <hr />

                    <form asp-action="Create">
                        <div class="form-group">
                            <label asp-for="PetName" class="control-label"></label>
                            <input asp-for="PetName" class="form-control" />
                            <span asp-validation-for="PetName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PetSpecies" class="control-label"></label>
                            <input asp-for="PetSpecies" class="form-control" />
                            <span asp-validation-for="PetSpecies" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PetBreed" class="control-label"></label>
                            <input asp-for="PetBreed" class="form-control" />
                            <span asp-validation-for="PetBreed" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PetSex" class="control-label"></label>
                            <input asp-for="PetSex" class="form-control" />
                            <span asp-validation-for="PetSex" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Age" class="control-label"></label>
                            <input asp-for="Age" class="form-control" />
                            <span asp-validation-for="Age" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PetImage" class="control-label"></label>
                            <input asp-for="PetImage" class="form-control" />
                            <span asp-validation-for="PetImage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PetProfileImagePath" class="control-label"></label>
                            <input asp-for="PetProfileImagePath" class="form-control" />
                            <span asp-validation-for="PetProfileImagePath" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>


            

                @section Scripts {
                    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                }
            </div>
        </div>
    </div>
</div>

Views/Pet/PetDashboard.cshtml
@model PetBook.Models.Pet
@{
    ViewData["Pet Profile"] = "Pet Profile";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>PetBook</title>

</head>




<body>
    
     
        <div class="container-fluid" style="background-color: transparent">

            <!--This is the container for the body render-->
            <div class="container-fluid">
                <div class="card mb-lg-1" style="max-width:1200px; background-color: transparent; border-width: 0px">
                    <div class="row">


                        <!--This is the profile image-->
                        <div class="col-md-3" style="padding: 30px">
                            <img src="~/Dog.jpg" alt="Pet Profile" class="img-thumbnail">

                            <!--This is the side navigation bar-->
                            <!--TODO-->
                            <ul class="nav flex-column">
                                <li class="nav-item" style="padding-top:10px">
                                    <a class="nav-link" asp-area="" asp-controller="MedicalFiles" asp-action="PetMedFile">@Model.PetName Medical File</a>
                                </li>
                                <!--TODO-->
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Veterinarian" asp-action="Details">@Model.PetName Veterinarian Profile</a>
                                </li>
                                <!--TODO-->
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="CreateCalendar">Add Event</a>
                                </li>
                                <!--TODO-->
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="EditCalendar">Edit Event</a>
                                </li>
                                <!--TODO-->
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="IndexCalendar">List Event</a>
                                </li>
                                <!--TODO-->
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Dashboard">Return to your Dashboard</a>
                                </li>
                                <!--TODO-->
                                <li class="nav-item">
                                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
                                </li>
                                
                            </ul>
                        </div>
                                                
                        <!--This is the Clients Name Heading-->
                        <div class="col-md-9" style="padding-left:50px; border:thin">
                            <div class="card-body" ; style="padding:20px">
                                <h2 class="card-deck">@Model.PetName<br /></h2>
                            </div>


                            <!--This is the Pets Biometric data cards-->
                        
                            <div class="row"></div>
                            <div class="card" style="width: 35rem; background-color: transparent; border-width: 0px">
                                <div class="card-body" ; style="padding:20px">
                                    <h5 class="card-title">Pet Id Number</h5><p class="card-text">@Model.PetId</p></br>

                                    <h5 class="card-title">Breed</h5><p class="card-text">@Model.PetBreed</p>

                                    <h5 class="card-title">Sex</h5><p class="card-text">@Model.PetSex</p>

                                    <h5 class="card-title">Species</h5><p class="card-text">@Model.PetSpecies</p>
                                </div>
                            </div>
                            
                            <div class="col-10" style="text-decoration-color:lime">
                                <td>
                                    <a asp-action="EditPet" asp-route-id="@Model.PetId">Edit Profile</a> |
                                </td>
                                <td>
                                    <a asp-action="RemovePet" asp-route-id="@Model.PetId">Delete Pet</a> |
                                </td>
                            </div>
                        </div>



                    </div>
                    </div>

                </div>
            </div>
    <br />
    <br />
            <!--Start of the events card that lists the calendar events of each pet on the Home Page / Dashboard-->

            <div class="card text-center" style="background-color:transparent">
                <div class="card" style="background-color:transparent">
                    <div class="card-body">

                        <h5 class="card-title">@Model.PetName Events Snap Shot</h5>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>
                        <p class="card-text"><partial>@Model.ClientPet</partial></p>

                        <a href="#" class="btn btn-outline-secondary">Calendar</a>
                    </div>
                </div>
            </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>

Views/Pet/PetIndex.cshtml
@model IEnumerable<PetBook.Models.Pet>


@{
    ViewData["My Pets"] = "List Pets";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


<div class="container-fluid" style="background-color: transparent">

    <!--This is the container for the body render-->
    <div class="container-fluid">
        <div class="card mb-lg-1" style="max-width:1200px; background-color: transparent; border-width: 0px">
            <div class="row">

                <!--This is the profile image-->
                <div class="col-md-3" style="padding: 30px">
                    <img src="~/ProfilePic.png" alt="User Profile" class="img-thumbnail">

                    <!--This is the side navigation bar-->
                    <!--TODO-->
                    <ul class="nav flex-column">
                        <li class="nav-item" style="padding-top:10px">
                            <a class="nav-link" asp-area="" asp-controller="Pet" asp-action="CreatePet">My Pets Profiles</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Veterinarians" asp-action="CreateVet">Veterinarian Profile</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="CreateCalendar">Add Event</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="EditCalendar">Edit Event</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="DeleteCalendar">Delete Event</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="SiteInformation"></a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
                        </li>
                    </ul>
                </div>
                <div class="col-7">
                    <h1>My Pets</h1>
                    <br />

                    <br />

                    <p>
                        <a asp-controller="Pet" asp-action="CreatePet">Create Pet Profile</a>
                    </p>


                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.PetId)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.PetName)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(ModelItem => item.PetId)
                                </td>
                                <td>
                                    @Html.DisplayFor(ModelItem => item.PetName)
                                </td>
                                <td>

                                    <a asp-action="PetDashboard" asp-route-id="@item.PetId">Pet Profile</a> |

                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>

Views/Pet/RemovePet.cshtml
@model PetBook.Models.Pet
@{
    ViewData["Title"] = "Remove a Pet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3>Are you sure you want to remove this pet?</h3>
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PetName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PetName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PetSpecies)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PetSpecies)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PetBreed)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PetBreed)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PetSex)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PetSex)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PetImage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PetImage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PetProfileImagePath)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PetProfileImagePath)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="PetId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>