Models/Veterinarian.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PetBook.Models
{
    public partial class Veterinarian
    {
        public Veterinarian()
        {
            ClientVet = new HashSet<ClientVet>();
        }
        [Display(Name = "Vet Id #")]
        public int VetId { get; set; }

        [Required]
        [Display(Name = "Vet Name")]
        public string VetName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Vet E-mail Address")]
        public string VetEMail { get; set; }

        [Required]
        [Display(Name = "Street Address")]
        public string VetStreetAddress { get; set; }

        [Required]
        [Display(Name = "Town or City")]
        public string TownOrCity { get; set; }

        [Required]
        [Display(Name = "State")]
        public string State { get; set; }

        [Required]
        [Display(Name = "Zip Code")]
        public int ZipCode { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required]
        [Display(Name = "Phone Number")]
        public string VetPhoneNumber { get; set; }
        public string VetProfileImagePath { get; set; }

        public virtual ICollection<ClientVet> ClientVet { get; set; }
    }
}

Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace PetBook.Controllers
{
    public class AppointmentController : Controller
    {
        // GET: Appointment
        public ActionResult ListEvent()
        {
            return View();
        }

        // GET: Appointment/Details/5
        public ActionResult DetailsEvent(int id)
        {
            return View();
        }

        // GET: Appointment/Create
        public ActionResult AddEvent()
        {
            return View();
        }

        // POST: Appointment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddEvent(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Appointment/Edit/5
        public ActionResult EditEvent(int id)
        {
            return View();
        }

        // POST: Appointment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditEvent(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Appointment/Delete/5
        public ActionResult DeleteEvent(int id)
        {
            return View();
        }

        // POST: Appointment/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteEvent(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using PetBook.Data;
using PetBook.Models;


namespace PetBook.Controllers
{
    public class PetController : Controller
    {
        private PetbookContext dbContext;

        public PetController(PetbookContext dbContext)
        {
            this.dbContext = dbContext;
        }

        // GET: Pet/Details/5
        public IActionResult PetIndex()
        {
            var model = dbContext.Client
                                        .Where(client => client.UserEMail == User.Identity.Name)
                                        .SingleOrDefault();

            if (model.UserEMail == User.Identity.Name)
            {

                return View(this.dbContext.Pet);
            }
        
            else
            {
                return Redirect("CreatePet");
            }
   
                
          
           
        }

        // GET: Pet/Create
        public IActionResult CreatePet()
        {
      
                return View();
           
        }

        // POST: Pet/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePetPost(Pet Pet)
        {
            try
            {
                dbContext.Add(Pet);
                dbContext.SaveChanges();

                return RedirectToAction("PetIndex");

             
            }
            catch
            {
                return View("PetIndex");
            }
        }

        // GET: Pet/Edit/5
        public IActionResult EditPet(int id)
        {

            var Pet = dbContext.Pet
                                      .Where(Pet => Pet.PetId == id)
                                      .SingleOrDefault();

            if (Pet.PetId == id)
            {

                return View(Pet);
            }
            else
            {
                return Redirect("PetIndex");
            }

        }

       

        // POST: Pet/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPetPost(Pet Pet)
        {
            try
            {
                dbContext.Update(Pet);
                dbContext.SaveChanges();

                return Redirect("PetIndex");


            }
            catch
            {
                return View("PetIndex");
            }
        }

        // GET: Pet/Delete/5
        public ActionResult RemovePet(int id)
        {
            var Pet = dbContext.Pet
                                     .Where(Pet => Pet.PetId == id)
                                     .SingleOrDefault();

            if (Pet.PetId == id)
            {

                return View(Pet);
            }
            else
            {
                return Redirect("PetIndex");
            }
           
        }

        // POST: Pet/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemovePet(Pet Pet)
        {
            try
            {
                dbContext.Remove(Pet);
                dbContext.SaveChanges();

                return RedirectToAction("PetIndex");


            }
            catch
            {
                return View("PetIndex");
            }
        }

        public ActionResult PetDashboard(int id)
        {
            var Pet = dbContext.Pet
                                      .Where(Pet => Pet.PetId == id)
                                      .SingleOrDefault();

            if (Pet.PetId == id)
            {
                
                return View(Pet);
            }
            else
            {
                return Redirect("PetIndex");
            }
           
        }
    }
}

Views/Veterinarian/Create.cshtml
@model PetBook.Models.Veterinarian

@{
    ViewData["Title"] = "Create Vet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="container-fluid" style="background-color: transparent">

    <!--This is the container for the body render-->
    <div class="container-fluid">
        <div class="card mb-lg-1" style="max-width:1200px; background-color: transparent; border-width: 0px">
            <div class="row">

                <!--This is the profile image-->
                <div class="col-md-3" style="padding: 30px">
                    <img src="~/ProfilePic.png" alt="User Profile" class="img-thumbnail">

                    <!--This is the side navigation bar-->
                    <!--TODO-->
                    <ul class="nav flex-column">
                        <li class="nav-item" style="padding-top:10px">
                            <a class="nav-link" asp-area="" asp-controller="Pet" asp-action="CreatePet">My Pets Profiles</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Veterinarian" asp-action="Create">Add New Veterinarian</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Appointment" asp-action="Create">Make Vet Appointment</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Veterinarian" asp-action="Edit">Edit Veterinarian Details</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Veterinarian" asp-action="Index">E-mail Your Veterinarian</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Veterinarian" asp-action="Delete">Remove Veterinarian</a>
                        </li>
                        <!--TODO-->
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
                        </li>
                    </ul>
                </div>

                <div class="col-6" style="padding-left: 50px">

                    <h1>Create</h1>

                    <h4>Veterinarian</h4>
                    <hr />
                    
                    
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="VetId" class="control-label"></label>
                            <input asp-for="VetId" class="form-control" />
                            <span asp-validation-for="VetId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="VetName" class="control-label"></label>
                            <input asp-for="VetName" class="form-control" />
                            <span asp-validation-for="VetName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="VetEMail" class="control-label"></label>
                            <input asp-for="VetEMail" class="form-control" />
                            <span asp-validation-for="VetEMail" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="VetStreetAddress" class="control-label"></label>
                            <input asp-for="VetStreetAddress" class="form-control" />
                            <span asp-validation-for="VetStreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TownOrCity" class="control-label"></label>
                            <input asp-for="TownOrCity" class="form-control" />
                            <span asp-validation-for="TownOrCity" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="State" class="control-label"></label>
                            <input asp-for="State" class="form-control" />
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Country" class="control-label"></label>
                            <input asp-for="Country" class="form-control" />
                            <span asp-validation-for="Country" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="VetPhoneNumber" class="control-label"></label>
                            <input asp-for="VetPhoneNumber" class="form-control" />
                            <span asp-validation-for="VetPhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="VetProfileImagePath" class="control-label"></label>
                            <input asp-for="VetProfileImagePath" class="form-control" />
                            <span asp-validation-for="VetProfileImagePath" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                  
                 

                    <div>
                        <a asp-action="Index">Back to List</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

Views/Veterinarian/Delete.cshtml
@model PetBook.Models.Veterinarian

@{
    ViewData["Title"] = "Delete Vet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Veterinarian</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetEMail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetEMail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetStreetAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetStreetAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TownOrCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TownOrCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetPhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetPhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetProfileImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetProfileImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VetId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Veterinarian/Details.cshtml
@model PetBook.Models.Veterinarian

@{
    ViewData["Title"] = "Details Vet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Veterinarian</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetEMail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetEMail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetStreetAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetStreetAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TownOrCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TownOrCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetPhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetPhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VetProfileImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VetProfileImagePath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.VetId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Veterinarian/Edit.cshtml
@model PetBook.Models.Veterinarian

@{
    ViewData["Title"] = "Edit Vet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h1>Edit</h1>

<h4>Veterinarian</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VetId" />
            <div class="form-group">
                <label asp-for="VetName" class="control-label"></label>
                <input asp-for="VetName" class="form-control" />
                <span asp-validation-for="VetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VetEMail" class="control-label"></label>
                <input asp-for="VetEMail" class="form-control" />
                <span asp-validation-for="VetEMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VetStreetAddress" class="control-label"></label>
                <input asp-for="VetStreetAddress" class="form-control" />
                <span asp-validation-for="VetStreetAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TownOrCity" class="control-label"></label>
                <input asp-for="TownOrCity" class="form-control" />
                <span asp-validation-for="TownOrCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VetPhoneNumber" class="control-label"></label>
                <input asp-for="VetPhoneNumber" class="form-control" />
                <span asp-validation-for="VetPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VetProfileImagePath" class="control-label"></label>
                <input asp-for="VetProfileImagePath" class="form-control" />
                <span asp-validation-for="VetProfileImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Veterinarian/Index.cshtml
@model IEnumerable<PetBook.Models.Veterinarian>

@{
    ViewData["Title"] = "Index Vet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VetEMail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VetStreetAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TownOrCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VetPhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VetProfileImagePath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VetEMail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VetStreetAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TownOrCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VetPhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VetProfileImagePath)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VetId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.VetId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.VetId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>